apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-cert
  namespace: {{ .Values.namespace }}
  labels:
    desafio: jackexperts
spec:
  secretName: domain-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.domain }}
  dnsNames:
  - {{ .Values.ingress.domain }}
