apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    desafio: jackexperts
    app: nginx
data:
  index.html: {{ .Values.nginx.customHtml }}
