apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    desafio: jackexperts
    app: nginx
data:
  index.html: {{ .Values.customHtml }}
  TIMELINE.md: |-
    {{- range $path := .Values.timelineMD }}
      {{ base (path.Base.$path) }}: |
      {{- $file := .Files.Get $path | nindent 4 }}
      {{ $file }}
    {{- end }}
