apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    desafio: jackexperts
    app: nginx
data:
  index.html: |
    {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
  index2.html: {{ .Values.nginx.indexHtml }}
  timeline.md: {{ .Values.nginx.timelineMd }}
