apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    desafio: jackexperts
data:
  index.html: {{ .Values.customHtml }}
  TIMELINE.md: {{ .Values.timelineMD }}