apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    desafio: jackexperts
data:
  index.html: |
    {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}