apiVersion: apps/v1
kind: Deployment
metada:
  name: {{ .Release.Name }}-deployment
  labels:
    desafio: jackexperts
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
    template:
      metadata:
        labels:
          app: {{ .Release.Name }}
          desafio: jackexperts
        spec:
          containers:
            - name: nginx
              image: "{{ .Value.image.repository }}:{{ .Values.image.tag }}"
              ports:
              - containerPort: 80
              volumeMounts:
              - name: html-volume
                mountPath: /usr/share/nginx/html
          volumes:
            - name: html-volume
              configMap:
                name: {{ .Release.Name }}-configmap
                
