apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    desafio: jackexperts
spec:
  rules:
    - host: {{ .Values.domain }}
      http: 
        paths: /
        - pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-service
              port:
                number: 80