namespace: desafio-jackexperts
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "84399f840d555d5acd6203280c748455aaa9d372"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
