namespace: desafio-nginx
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "98dead97b8698ab6ca639f2c2f2fb525648677e9"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
persistence:
  enabled: false
