namespace: desafio-jackexperts
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "1b7a42e861aa856ba2bd1739c0aa14f8daaca5aa"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: "25%"

