namespace: desafio-jackexperts
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "c60851a21e3c8cdfffcce303ef11495fba930d74"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
