replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "c2c3b150b43d69272785a4dd47d1223e17efbf3c"
service:
  type: ClusterIP
  port: 8080
domain:
namespace: desafio-nginx
customHtml: |-
  {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
