namespace: desafio-jackexperts
replicasCount: 1 
image:
  repository: asolheiro/desafio-jackexperts
  tag: "135414d296559dceb3e0972d7a71abdf1a19ca81"
service:
  type: ClusterIP 
  port: 8080 
traefik:
  service:
    type: LoadBalancer 
    externalIP: "177.93.134.211" 
ingress:
  domain: "armandosolheiro.xyz" 
securityContext:
  runAsUser: 1001 
  runAsGroup: 1001 
  allowPrivilegeEscalation: false
