namespace: desafio-nginx # namespace da aplicação
replicasCount: 1 # número de replicas
image:
  repository: asolheiro/desafio-jackexperts
  tag: "7091388ad4a1ba6846657b4e54c5b71dbea86f3b"
service:
  type: ClusterIP # tipo do service criado
  port: 8080 # porta do service criado
traefik:
  service:
    type: LoadBalancer # tipo do service
    externalIP: "177.93.134.211" # IP da VM que hospeda o Cluster
ingress:
  domain: "armandosolheiro.xyz" # domínio que aponta para o cluster
securityContext:
  runAsUser: 1001 # informações sobre o usuário criado no Dockerfile
  runAsGroup: 1001 # informações sobre o usuário criado no Dockerfile
  allowPrivilegeEscalation: false # impede privilégios adicionais no contêiner
