replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "59c9a30de913de254717e81d4111d08a57cba0ac"
service:
  type: ClusterIP
  port: 8080
domain:
namespace: desafio-nginx
customHtml: |-
  {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
