replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "11094a9432e47aef5d511d0dcd9e86741193dcd4"
service:
  type: ClusterIP
  port: 8080
domain:
namespace: desafio-nginx
customHtml: |-
  {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
