namespace: desafio-jackexperts
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "18d076ace14bffe6c086842bc36b6406e31f3ec4"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: "25%"
