replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "a9e3694eace5aff3e3a9688d0d27eb67704904ae"
service:
  type: ClusterIP
  port: 8080
domain:
customHtml: |-
  {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
