namespace: desafio-nginx
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "7b6a0d050911b1a0ccc359f60c35181f45227740"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
persistence:
  enabled: false
