replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "810bb076e35981d55809769103f572d6c52bc2f6"
service:
  type: ClusterIP
  port: 8080
domain:
customHtml: |-
  {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
