replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "ac22ed3dcb712c2137f90afd8b6e0a5d20bf58eb"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
namespace: desafio-nginx
customHtml: |-
  {{ include "desafio-jackexperts.index.html.tpl" . | indent 4 }}
timelineMD: |-
  {{ include "desafio-jackexperts.TIMELINE.mds.tpl" . }}
