namespace: desafio-jackexperts
replicasCount: 1
image:
  repository: asolheiro/desafio-jackexperts
  tag: "3f6a331f296daa341ebac4f4476a52523e8ba575"
service:
  type: ClusterIP
  port: 8080
traefik:
  service:
    type: LoadBalancer
    externalIP: "177.93.134.211"
ingress:
  domain: "armandosolheiro.xyz"
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
